apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechTalk-With-Nathan/gitops-monitoring-ai
    targetRevision: HEAD
    path: ai-agent/ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
